line: kodo
limit: 3
streamers:
    copyright: 1
    source:
    tid: 27
    cover: ""
    title:
    desc_format_id: 0
    desc:
    dynamic: ""
    subtitle:
      open: 0
      lan: ""
    tag: ""
    dtime:
    open_subtitle: false
